In [2]:
pip install numpy

     ---------------------------------------- 14.7/14.7 MB 3.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [41]:
import numpy as np

In [4]:
a = [1,2,3,4]

In [5]:
a

[1, 2, 3, 4]

In [6]:
type(a)

list

In [7]:
b = np.array(a)

In [8]:
b

array([1, 2, 3, 4])

In [9]:
type(b)

numpy.ndarray

In [15]:
c =np.array([[1,2,3,4],[5,6,7,8]])

In [16]:
type (c)

numpy.ndarray

In [17]:
c.ndim

2

In [18]:
b.ndim

1

In [19]:
np.arange(1,10,3)

array([1, 4, 7])

In [20]:
np.arange( start= 1 , stop = 10 , step=1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange (5,16,5 , dtype= float)

array([ 5., 10., 15.])

In [25]:
np.zeros([2,3,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [26]:
np.zeros([2,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [27]:
np.ones([2,3,3])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [31]:
np.linspace(2,3,5 ,endpoint=False , retstep=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [34]:
np.eye(N=4 , M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [39]:
np.eye(N=4, M=5 , k=4)

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
np.random.rand(3,3)

array([[0.1647586 , 0.78078303, 0.44125789],
       [0.30584484, 0.29686945, 0.91035969],
       [0.00757611, 0.81915174, 0.54478087]])

In [58]:
np.random.rand(3,3)

array([[0.5740126 , 0.11578337, 0.89294383],
       [0.55141324, 0.72609856, 0.92381655],
       [0.37148865, 0.98986506, 0.73043974]])

In [72]:
b = np.random.randint(1,5, size=5 , )

In [74]:
np.shape(b)

(5,)

In [83]:
arr = np.array ([[1,2,3,4],[4,5,6,7], [9,10,11,12]])

In [84]:
arr

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 9, 10, 11, 12]])

In [86]:
np.shape(arr)

(3, 4)

In [90]:
 d =arr.reshape(4,3)

In [91]:
d

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  9],
       [10, 11, 12]])

In [92]:
np.shape(d)

(4, 3)