In [7]:
import numpy as np

In [8]:
a = np.array([1, 2, 3])

In [9]:
a

array([1, 2, 3])

In [12]:
arr= np.arange(10,30,2)

In [13]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((5,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.ones((5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [24]:
b=np.linspace(5,6,10)

In [25]:
b

array([5.        , 5.11111111, 5.22222222, 5.33333333, 5.44444444,
       5.55555556, 5.66666667, 5.77777778, 5.88888889, 6.        ])

In [26]:
c=np.linspace(5,6,5)
c

array([5.  , 5.25, 5.5 , 5.75, 6.  ])

In [29]:
c=np.linspace(5,6,10 , retstep=True)

In [30]:
c

(array([5.        , 5.11111111, 5.22222222, 5.33333333, 5.44444444,
        5.55555556, 5.66666667, 5.77777778, 5.88888889, 6.        ]),
 0.1111111111111111)

In [35]:
np.eye(5,5 , dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [36]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [37]:
np.eye(3,5,1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [38]:
import random

In [43]:
np.random.rand(3,5)

array([[0.24080645, 0.57226516, 0.82603823, 0.54469217, 0.49146795],
       [0.95097767, 0.24109769, 0.77035958, 0.34501514, 0.44079165],
       [0.29317739, 0.23393532, 0.63833891, 0.32783619, 0.08289031]])

In [48]:
d=np.random.randn(3,5)

In [49]:
print(d.shape)

(3, 5)


In [52]:
e=np.array(([1,2,3],[4,5,6],[7,8,9],[10,11,12]))
e

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
e.shape

(4, 3)

In [54]:
f=e.reshape(2,6)
f

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [55]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])

In [56]:
x

array([[1, 2, 3],
       [3, 4, 5]])

In [57]:
y

array([[1, 2, 3],
       [3, 4, 5]])

In [58]:
print (x+y)

[[ 2  4  6]
 [ 6  8 10]]


In [59]:
print (x-y)

[[0 0 0]
 [0 0 0]]


In [60]:
print(x*y)

[[ 1  4  9]
 [ 9 16 25]]


In [61]:
print (x/y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [62]:
arr=np.array([[1,2,3],[2,3,4],[3,4,5]])

In [63]:
arr1=np.array([[4,5,6]])

In [64]:
arr

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [65]:
arr1

array([[4, 5, 6]])

In [66]:
np.append(arr=arr, values=arr1, axis=0)

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [72]:
arr

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [68]:
arr2=np.array([[1],[2],[3]])

In [70]:
arr2

array([[1],
       [2],
       [3]])

In [75]:
np.append(arr=arr, values=arr2, axis=1)

array([[1, 2, 3, 1],
       [2, 3, 4, 2],
       [3, 4, 5, 3]])

In [76]:
np.concatenate ((arr,arr1))

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [78]:
np.concatenate ((arr,arr2), axis=1)

array([[1, 2, 3, 1],
       [2, 3, 4, 2],
       [3, 4, 5, 3]])

In [28]:
c

(array([5.        , 5.02040816, 5.04081633, 5.06122449, 5.08163265,
        5.10204082, 5.12244898, 5.14285714, 5.16326531, 5.18367347,
        5.20408163, 5.2244898 , 5.24489796, 5.26530612, 5.28571429,
        5.30612245, 5.32653061, 5.34693878, 5.36734694, 5.3877551 ,
        5.40816327, 5.42857143, 5.44897959, 5.46938776, 5.48979592,
        5.51020408, 5.53061224, 5.55102041, 5.57142857, 5.59183673,
        5.6122449 , 5.63265306, 5.65306122, 5.67346939, 5.69387755,
        5.71428571, 5.73469388, 5.75510204, 5.7755102 , 5.79591837,
        5.81632653, 5.83673469, 5.85714286, 5.87755102, 5.89795918,
        5.91836735, 5.93877551, 5.95918367, 5.97959184, 6.        ]),
 0.02040816326530612)

In [11]:
arr

array([10, 13, 16, 19, 22, 25, 28])

array([1, 2, 3])